all:
	#g++ main.cpp -I/usr/include/GL/ -I ProbCon2.h -o spikes -lGL -lglut
	g++ main.cpp -framework OpenGL -framework GLUT -I ProbCon2.h -o spikes 
	#clang main.cpp -I ProbCon2.h -framework OpenGL -framework GLUT -o spikes
